---
kind: pipeline
type: docker
name: winglang

steps:
  - name: ECR login
    image: amazon/aws-cli
    environment:
      AWS_REGION:
        from_secret: aws_region
    commands:
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION > .docker-login

  - name: ECR pull
    image: docker
    environment:
      AWS_REGION:
        from_secret: aws_region
      AWS_ACCOUNT:
        from_secret: aws_account
      DOCKER_REPO:
        from_secret: docker_repo
    commands:
      - cat .docker-login | docker login -u AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com 2>/dev/null
      - rm .docker-login
      - docker pull $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_REPO:dev
      - docker tag $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_REPO:dev winglang-dev
    volumes:
      - name: dind
        path: /var/run/docker.sock

  - name: wingrr tests
    image: winglang-dev
    pull: never
    commands:
      - bash wingrr/scripts/build.sh

volumes:
  - name: dind
    host:
      path: /var/run/docker.sock
