name: DocsTest

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "docs/**"
      - "logo/**"
  push:
    branches:
      - main
      - dev
  workflow_dispatch: {}

jobs:
  build:
    name: "Build"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Compress Docs
        run: tar -czvf docs.tgz docs/*

      - name: Upload Docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs.tgz

  publish:
    name: Publish
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3

      - run: ls -al docs
      - run: mkdir dist

      - name: Compute Checksums
        run: |
          mv docs/* dist/
          cd dist

          echo '' >> ../CHANGELOG.md
          echo '### SHA-1 Checksums' >> ../CHANGELOG.md
          echo '```' >> ../CHANGELOG.md
          sha1sum --binary * >> ../CHANGELOG.md
          echo '```' >> ../CHANGELOG.md
          cat ../CHANGELOG.md

      - run: ls -al dist/
