name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODEJS_VERSION: "16.x"
  PYTHON_VERSION: "3.10"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x64, x86]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Infrastructure Binaries
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "monadahq/winglang-infra"
          tag: "development"
          fileName: "libnode-${{ matrix.os }}-${{ matrix.arch }}.zip"
          token: ${{ secrets.WINGLANG_GITHUB_TOKEN }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup Private NPM with Github
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          registry-url: "https://npm.pkg.github.com"
      - name: Environment Information
        run: npx envinfo
      - name: Build Wing
        env:
          RUSTFLAGS: "-C target-cpu=native"
          NODE_AUTH_TOKEN: ${{ secrets.WINGLANG_GITHUB_TOKEN }}
        run: |
          pushd wingc
            cargo test --release -- --nocapture
            cargo build --release
          popd

          mkdir -p wingr/vendor/node
          unzip -q libnode-${{ matrix.os }}-${{ matrix.arch }}.zip -d wingr/vendor/node
          pushd wingr
            npm install
            npm test
          popd
