name: Build

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "docs/**"
      - "logo/**"
      - "*.md"
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      # Testing runs out of memory without this
      NODE_OPTIONS: "--max-old-space-size=4096"
      RUST_VERSION: "1.67.1"
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: |
            x86_64-unknown-linux-gnu
            wasm32-wasi
          components: rustfmt,clippy,rust-std

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build:ci

      - name: Install Wing Globally
        run: npm install -g ./apps/wing

      - run: wing compile examples/tests/valid/hello.w -t tf-aws
