name: Canary Testing
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}
  release:
    types:
      - published

jobs:
  install:
    name: Installation User Flow
    strategy:
      fail-fast: true
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 18
          - 19
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Minimal Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Get Latest Wing Version
        id: get-version
        run: |
          echo version=$(npm view winglang version) >> $GITHUB_OUTPUT
      - name: Install Wing
        run: |
          ./scripts/setup_wing.mjs -g --version ${{ steps.get-version.outputs.version }}
      - name: Run Test
        run: |
          wing test examples/tests/valid/test_bucket.w
