name: SDK Spec Testing
# on:
#   schedule:
#     - cron: "0 * * * *"
#   workflow_dispatch: {}
#   release:
#     types:
#       - published

on:
  push:
    branches:
      - tsuf/sdk-tests-github-action

jobs:
  install:
    name: Installation User Flow
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: winglang/wing
          ref: tsuf/sdk-tests-github-action
      # - name: move
      #   run: git checkout origin/tsuf/sdk-tests-github-action
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Get Latest Wing Version
        id: get-version
        run: |
          echo version=$(npm view winglang version) >> $GITHUB_OUTPUT
      - name: Install Wing
        run: |
          npm install -g winglang@${{ steps.get-version.outputs.version }}
      - name: Run tests
        run: |
          ls
          cd examples/tests/sdk_tests
          find . -type f -name "*.w" | while read file; do
            wing test -t tf-aws "$file"
          done
